services:
  verifier:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        SKIP_TESTS: "true"
    container_name: verifier
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      SERVER_PORT: 8082
      VERIFIER_FRONTEND_PORTALURL: http://localhost:4200
    restart: unless-stopped

  portal-acceso:
    build:
      context: ../../eudistack-portal-acceso-ui
      dockerfile: Dockerfile
    container_name: portal-acceso
    ports:
      - "4200:80"
    volumes:
      - ../../eudistack-portal-acceso-ui/themes/dome.json:/usr/share/nginx/html/assets/theme.json:ro
    depends_on:
      - verifier
    restart: unless-stopped
